#!/usr/bin/env bash


pvenode_hostname=$1
pvenode_domain=$2
pvenode_ip_address=$3
pvebridge_ip_address=$4
pvebridge_gateway=$5



export DEBIAN_FRONTEND=noninteractive
export APT_LISTCHANGES_FRONTEND=none
export APT_OPTIONS=' -y --allow-downgrades --allow-remove-essential --allow-change-held-packages -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold '
export APT_OPTIONS_NEW=' -y --allow-downgrades --allow-remove-essential --allow-change-held-packages -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew '



configura_vmbr0_eth2() {

  cat - | sudo tee /etc/network/interfaces >/dev/null  <<EOF
# network interface settings; autogenerated
# Please do NOT modify this file directly, unless you know what
# you're doing.
#
# If you want to manage parts of the network configuration manually,
# please utilize the 'source' or 'source-directory' directives to do
# so.
# PVE will preserve these directives, but will NOT read its network
# configuration from sourced files, so do not attempt to move any of
# the PVE managed interfaces into external files!

source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
#NAT hacia Internet

#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth1
iface eth1 inet static
      address ${pvenode_ip_address}
      netmask 255.255.255.0
# Red hipervisores

#VAGRANT-END


auto vmbr0
iface vmbr0 inet static
	address ${pvebridge_ip_address}/24
	gateway ${pvebridge_gateway}
	bridge-ports eth2
	bridge-stp off
	bridge-fd 0
#Red de servicio

EOF


#sudo service networking restart
sudo ifreload -a
sudo rm -f /etc/network/interfaces.new
}


configura_vmbr0_eth2
