# -*- mode: ruby -*-
# vi: set ft=ruby :

# Para aprovechar este Vagrantfile necesita Vagrant y Virtualbox instalados:
#
#   * Virtualbox
#
#   * Vagrant
#
#   * Plugins de Vagrant:
#       + vagrant-proxyconf y su configuracion si requiere de un Proxy para salir a Internet
#       + vagrant-cachier
#       + vagrant-disksize
#       + vagrant-hostmanager
#       + vagrant-reload
#       + vagrant-share
#       + vagrant-vbguest

VAGRANTFILE_API_VERSION = "2"

HOSTNAME = "pve1"
DOMAIN   = "infra.ballardini.com.ar"



$post_up_message_pvenode = <<POST_UP_MESSAGE
------------------------------------------------------
Cluster Proxmox PVE: solo un nodo simple

URLS:
 - host only - https://pve1.infra.ballardini.com.ar:8006/
 - host only - https://192.168.33.11:8006/

credenciales Web: root / admin

------------------------------------------------------
POST_UP_MESSAGE


$post_up_message_ws = <<POST_UP_MESSAGE
------------------------------------------------------
Cluster Proxmox PVE: estacion de control con Terraform

 - ip address: 192.168.33.10

credenciales SSH: vagrant / vagrant

------------------------------------------------------
POST_UP_MESSAGE


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true

    # uso cachier con NFS solamente si el hostmanager gestiona los nombres en /etc/hosts del host
    if Vagrant.has_plugin?("vagrant-cachier")

      config.cache.auto_detect = false
      # W: Download is performed unsandboxed as root as file '/var/cache/apt/archives/partial/xyz' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

      config.cache.synced_folder_opts = {
        owner: "_apt"
      }
      # Configure cached packages to be shared between instances of the same base box.
      # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
      config.cache.scope = :box
   end

  end

 config.vm.define HOSTNAME do |srv|

    srv.vm.box = "debian/buster64"

    ## eth0: NAT network y default gateway , adapter: 1
    ## eth1:
    srv.vm.network "private_network", ip: "192.168.33.11", name: 'vboxnet0', adapter: 2  # red de los hipervisores eth1

    ## eth2: se sumara a vmbr0
    #srv.vm.network "private_network", ip: "192.168.44.11", name: 'vboxnet1', auto_config: false # red de servicio eth2
    srv.vm.network "private_network", ip: "192.168.44.11", name: 'vboxnet1', adapter: 3, auto_config: false # red de servicio eth2


    srv.vm.post_up_message = $post_up_message_pvenode
    srv.vm.boot_timeout = 300
    srv.vm.box_check_update = true
    srv.ssh.forward_agent = true
    srv.ssh.forward_x11 = true
    srv.vm.hostname = HOSTNAME

    if Vagrant.has_plugin?("vagrant-hostmanager")
      srv.hostmanager.aliases = %W(#{HOSTNAME}.#{DOMAIN} )
    end

    if Vagrant.has_plugin?("vagrant-vbguest") then
        srv.vbguest.auto_update = true
        srv.vbguest.no_install = false
    end

    srv.vm.synced_folder ".", "/vagrant", disabled: false, SharedFoldersEnableSymlinksCreate: false, type: :virtualbox


    srv.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.cpus = 2
      vb.memory = "4096"
      # https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm mas parametros para personalizar en VB
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]

      vb.customize ["modifyvm", :id, "--hostonlyadapter2", "vboxnet0"]  # eth1
      vb.customize ["modifyvm", :id, "--hostonlyadapter3", "vboxnet1"]  # eth2

      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    end

    srv.vm.provision "instala_ifupdown2", type: "shell" do |s|
        s.privileged = false
        s.inline = <<-SHELL
          export DEBIAN_FRONTEND=noninteractive

          sudo -E apt-get install ifupdown2 -y
          # ni se te ocurra eliminar ifupdown: se pierde el acceso SSH a la VM
          #
          sudo sed -i 's@source-directory /etc/network/interfaces.d@source /etc/network/interfaces.d/*@' /etc/network/interfaces
          sudo systemctl restart networking
        SHELL
    end

    srv.vm.provision "instala_pve", type: "shell", privileged: false, path: "provision/instala-pve6.sh"
    srv.vm.provision :reload
    srv.vm.provision "post_instala_pve", type: "shell", privileged: false, path: "provision/post-instala-pve6.sh"

  end


  config.vm.define "ws" do |cliente|

    cliente.vm.box = "ubuntu/focal64"
    cliente.vm.network "private_network", ip: "192.168.33.10", name: 'vboxnet0'  # red de los hipervisores enp0s8 para acceder desde pc enp0s8

    cliente.vm.post_up_message = $post_up_message_ws
    cliente.vm.boot_timeout = 180
    cliente.vm.box_check_update = true
    cliente.ssh.forward_agent = true
    cliente.ssh.forward_x11 = true
    cliente.vm.hostname = "ws"

    if Vagrant.has_plugin?("vagrant-hostmanager")
      cliente.hostmanager.aliases = %W(#{HOSTNAME}.#{DOMAIN} )
    end

    if Vagrant.has_plugin?("vagrant-vbguest") then
        cliente.vbguest.auto_update = true
        cliente.vbguest.no_install = false
    end

    cliente.vm.synced_folder ".", "/vagrant", disabled: false, SharedFoldersEnableSymlinksCreate: false, type: :virtualbox

    cliente.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.cpus = 1
      vb.memory = "1024"
    end

    cliente.vm.provision "instala_ws", type: "shell", privileged: false, path: "provision/instala-ws.sh"
  end


    ##
    # Aprovisionamiento para todas las VMs, corre antes que la provision especifica de cada VM
    #
    config.vm.provision "fix-no-tty", type: "shell" do |s|
        s.privileged = false
        s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
    end

    config.vm.provision "actualiza", type: "shell" do |s|  # http://foo-o-rama.com/vagrant--stdin-is-not-a-tty--fix.html
        s.privileged = false
        s.inline = <<-SHELL
          export DEBIAN_FRONTEND=noninteractive
          export APT_LISTCHANGES_FRONTEND=none
          export APT_OPTIONS=' -y --allow-downgrades --allow-remove-essential --allow-change-held-packages -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold '

          sudo -E apt-get --purge remove apt-listchanges -y > /dev/null 2>&1
          sudo -E apt-get update -y -qq > /dev/null 2>&1
          sudo dpkg-reconfigure --frontend=noninteractive libc6 > /dev/null 2>&1

          sudo -E apt-get install linux-image-amd64 ${APT_OPTIONS}  || true
          sudo -E apt-get upgrade ${APT_OPTIONS} > /dev/null 2>&1
          sudo -E apt-get dist-upgrade ${APT_OPTIONS} > /dev/null 2>&1

          sudo -E apt-get autoremove -y > /dev/null 2>&1
          sudo -E apt-get autoclean -y > /dev/null 2>&1
          sudo -E apt-get clean > /dev/null 2>&1
        SHELL
    end

    config.vm.provision "ssh_pub_key", type: :shell do |s|
      begin
          ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
          s.inline = <<-SHELL
            mkdir -p /root/.ssh/
            touch /root/.ssh/authorized_keys
            echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
            echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
          SHELL
      rescue
          puts "No hay claves publicas en el HOME de su pc"
          s.inline = "echo OK sin claves publicas"
      end
    end

end
